{% set name = "unimport" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unimport-{{ version }}.tar.gz
  sha256: e0c8f854acb6322d609243a4ec864a5961f81d976e28383b0cafd36a3385aa12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - unimport=unimport.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - pip
  run:
    - python >={{ python_min }},<3.12
    - toml <1,>=0.9.0
    - dataclasses <1,>=0.5
    - typing-extensions <4,>=3.7.4
    - libcst <1,>=0.3.0
    - pathspec <1,>=0.10.1

test:
  imports:
    - unimport
  commands:
    - pip check
    - unimport --help
  requires:
    - pip

    # pyproject.toml exclude these at build time for noarch, adding back here for pip check
    - libcst <1,>=0.3.0
    - pathspec >=0.5.0,<1
    - python {{ python_min }}

about:
  home: https://github.com/hakancelikdev/unimport
  doc_url: https://unimport.hakancelik.dev/
  summary: The ultimate linter and formatter for removing unused import statements in your code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
